const TIPO_OPERACION = {
    SUMA:               'SUMA',
    RESTA:              'RESTA',
    MULTIPLICACION:     'MULTIPLICACION',
    DIVISION:           'DIVISION',
    POTENCIA:           'POTENCIA',
    NEGATIVO:           'NEGATIVO',
    MODULO:             'MODULO',
    IGUALIGUAL:         'IGUALIGUAL',
    DIFERENTE:          'DIFERENTE',
    MENOR:              'MENOR',
    MENORIGUAL:         'MENORIGUAL',
    MAYOR:              'MAYOR',
    MAYORIGUAL:         'MAYORIGUAL',
    OR:                 'OR',
    AND:                'AND',
    NOT:                'NOT',
    LOWER:              'LOWER',
    UPPER:              'UPPER',
    TSTRING:            'TSTRING',
    TYPEOF:             'TYPEOF',
    ROUND:              'ROUND',
    TRUNCATE:           'TRUNCATE',
    LENGTH:             'LENGTH',
    CASTEO:             'CASTEO',
    TERNARIO:           'TERNARIO'
}
module.exports= TIPO_OPERACION;